apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: store
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: store
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/micro-default: "true"
        io.kompose.service: store
    spec:
      containers:
        - args:
            - bash
            - -c
            - python ./manage.py makemigrations && python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8000
          image: store
          name: store
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: store-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: store-cm0
          name: store-cm0
